version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - REPOSITORY_URI=108040610828.dkr.ecr.us-east-1.amazonaws.com/demo-repo
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 108040610828.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - echo "Sagar@0525" | docker login -u sagar0525 --password-stdin
      - docker build -t demo-repo .
      - docker tag demo-repo:latest 108040610828.dkr.ecr.us-east-1.amazonaws.com/demo-repo:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker images
      - docker push 108040610828.dkr.ecr.us-east-1.amazonaws.com/demo-repo:latest
      - echo Writing image definitions file...
      - printf '[{"name":"web-cont","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
    files: imagedefinitions.json
